### ISSUE TITLE
Start Problem Wifirst

### ISSUE THREAD

**Issue by bzhdudu** [HuguesGuilleus/wifirst#2]
Hello,
First of all, thank you for your contribution, your code! 
But I'm on a problem, I can't adapt it to the wifirst network.
[Screen Problem Wifirst](https://zupimages.net/up/21/50/y1n4.png)
I'm new to coding and sorry for my English! thank you in advance for your help!

**Comment by HuguesGuilleus** [comment]
Hello,
Thanks to use my program.
Between two run of this program, do you go to the portal?

The normal usage is: `wifirst -l login -p password`.

*PS: Je pense que vous parlez français, vous pouvez répondre dans cette belle langue.*
