### ISSUE TITLE
Script fonctionne-t-il toujours ? Test au CROUS.

### ISSUE THREAD

**Issue by HoustonLFB** [HuguesGuilleus/wifirst#3]
Bonjour,
Tout d'abord, merci pour ce script. Je suis dans le réseau du CROUS, l’accès au réseau se fait via Ethernet ou Wifi, puis je dois me connecter au portail captif Wifirst. Dans mon cas, la page de connexion est https://planetcampus.wifirst.net. Je pense que le script ne doit pas être fait pour l'environnement du CROUS mais je tente quand même de demander s'il est toujours à jours si c'était le cas ?
Sinon, de quelle manière devrais-je le modifier pour l'adapter à ma situation ? Je comprend que je devrai le recompiler pour créer l'exécutable.
Je l'ai testé sur Debian11 et voici le résultat que j'ai eu:
```
# ./wifirst_linux_amd64 -l ***@gmail.com -p ***

2023/04/16 22:48:19 GET https://wireless.wifirst.net:8099/index.txt
2023/04/16 22:48:49 Get "https://wireless.wifirst.net:8099/index.txt": dial tcp 10.212.0.1:8099: i/o timeout
```

**Comment by HuguesGuilleus** [comment]
Bonjour,
Malheureusement je n'ai pas conçu ce script pour ce portail que je ne connaissais pas. Du coup c'est normal qu'il ne marche pas.

La solution serait de faire de la rétro-ingénierie sur les requêtes vers ce portail, puis de mettre une option dans le programme. Je regarde ça bientôt.

**Comment by HuguesGuilleus** [comment]
Bonjour, désolé du retard.
J'ai ajouté une détection du portail, donc cela devrait fonctionner pour le CROUS.

Si cela ne marche pas, il me faudrait la liste de URL quand tu te connectes sur le portail Wifirst du CROUS (navigateur>F12>réseau pour afficher les informations).

**Comment by HoustonLFB** [comment]
Bonjour, je te remercie. J’essaierai quand je rentrerai des vacances.

**Comment by HoustonLFB** [comment]
Bonjour, 
Ça fonctionne ! J'ai testé plusieurs fois sur plusieurs machines. Je vais lancer ce script toute les 5 minutes avec un cron pour qu'il se reconnecte automatiquement.
Merci beaucoup, ça m'enlève une sacré épine du pied.
